FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

ENV NODE_ENV=production
ENV PORT=3000
ENV JWT_SECRET=9a+0f8uiYTfrSY1nkBVdXAmQI7QwW+EEFsfxBYkGGA4=
ENV SMTP_HOST=localhost
ENV SMTP_PORT=25
ENV CLIENT_DIR=/app/clients/osteopathie-limbach
ENV SITE_URL=https://html.osteopathie-limbach.de
ENV EDITOR_EMAIL=mail@panoart360.de

EXPOSE 3000

CMD ["npm", "start"]
